import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          inter.variable,
          "text-zinc-700 grid grid-cols-[20rem_1fr] h-screen dark:bg-neutral-900 dark:text-neutral-100"
        )}
      >
        <ThemeProvider attribute="class">
          <Sidebar />
          <main className="p-4 overflow-auto flex flex-col">
            <header className="bg-green-600 text-white p-5 rounded-md">
              <Navbar />
            </header>
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
